### ISSUE TITLE
no documentation !!

### ISSUE THREAD

**Issue by hboumedane** [Tirasa/SAML2ServiceProvider#1]
Hello,

is there any doc that we can use to config the service or to explain how to use this app.

**Comment by fmartelli** [comment]
Hi, unfortunately no doc is available. A dedicated post is coming.
See below an improvised "getting stated". Fell free to ask for information, open new issue and contribute by providing pull requests.

SAML2ServiceProvider is a simple web app implementing a service provider SAML2.
SAML2 specification has not been fully implemented.  Till today, the implementation has been tested with shibboleth and OpenAM identity providers. 

You can configure the software editing 
https://github.com/Tirasa/SAML2ServiceProvider/blob/master/src/main/resources/services.properties

storepass, keypass and certificate.alias are for the keystore storing certificate for artifact signing and encryption. Into the same directory put your keystore.

By default identity provider metadatas are retrieved into /tmp directory. See
https://github.com/Tirasa/SAML2ServiceProvider/blob/master/src/main/java/net/tirasa/saml/context/SPContextListener.java

This folder (/tmp) has not been parametrised yet.
